@extends('layouts.app')
@section('title','Admin VidoHub')
@section('content')
<div class="heading"><div><h1>Manajemen Video</h1><p>Kelola sumber, model, dan kategori koleksi VidoHub.</p></div><a class="btn primary" href="#video-form">＋ Tambah Video</a></div>
<div class="stats"><div class="stat"><small>Total video</small><strong>{{ $totalVideos }}</strong></div><div class="stat"><small>Kategori terdaftar</small><strong>{{ $categories->count() }}</strong></div><div class="stat"><small>Model terdaftar</small><strong>{{ $models->count() }}</strong></div></div>
<div class="admin-columns">
<section class="panel admin-section"><h2>Manajemen Kategori</h2><form action="{{ route('admin.categories.store') }}" method="POST" class="quick-form">@csrf<input name="name" maxlength="80" required placeholder="Nama kategori baru"><select name="page_key" title="Kategori default navbar"><option value="">Kategori biasa</option><option value="fav">Fav</option><option value="edukasi">Edukasi</option><option value="tutorial">Tutorial</option><option value="music">Music</option><option value="lucu">Lucu</option></select><button class="btn primary">＋ Tambah</button></form><div class="tag-list">@forelse($categories as $category)<span class="pill tag-item">{{ $category->name }}@if($category->page_key)<small> ({{ ucfirst($category->page_key) }})</small>@endif <form method="POST" action="{{ route('admin.categories.destroy',$category) }}" onsubmit="return confirm('Hapus kategori ini?')">@csrf @method('DELETE')<button aria-label="Hapus kategori">×</button></form></span>@empty<span class="muted">Belum ada kategori.</span>@endforelse</div></section>
<section class="panel admin-section"><h2>Manajemen Model</h2><form action="{{ route('admin.models.store') }}" method="POST" class="quick-form">@csrf<input name="name" maxlength="120" required placeholder="Nama model baru"><button class="btn primary">＋ Tambah</button></form><div class="tag-list">@forelse($models as $model)<span class="pill model-pill tag-item">{{ $model->name }} <form method="POST" action="{{ route('admin.models.destroy',$model) }}" onsubmit="return confirm('Hapus model ini?')">@csrf @method('DELETE')<button aria-label="Hapus model">×</button></form></span>@empty<span class="muted">Belum ada model.</span>@endforelse</div></section>
</div>
<section class="panel admin-section" id="video-form"><h2 id="form-heading">Tambah video baru</h2><form id="videoForm" action="{{ route('admin.videos.store') }}" method="POST">@csrf
<input type="hidden" name="duration" id="duration"><div class="form-grid"><div class="field"><label>Nama video *</label><input name="title" id="title" maxlength="180" placeholder="Nama otomatis dari file"></div>
<div class="field"><label>Kategori * <span class="help">(bisa pilih beberapa)</span></label><input class="tag-search" data-target="category-options" placeholder="Cari kategori…"><div class="check-list" id="category-options">@foreach($categories as $category)<label data-name="{{ strtolower($category->name) }}"><input type="checkbox" name="category_ids[]" value="{{ $category->id }}"> {{ $category->name }}</label>@endforeach</div></div>
<div class="field"><label>Model * <span class="help">(bisa pilih beberapa)</span></label><input class="tag-search" data-target="model-options" placeholder="Cari model…"><div class="check-list" id="model-options">@foreach($models as $model)<label data-name="{{ strtolower($model->name) }}"><input type="checkbox" name="model_ids[]" value="{{ $model->id }}"> {{ $model->name }}</label>@endforeach</div></div>
<div class="field full"><label>Sumber video *</label><div class="source-tabs"><label><input type="radio" name="source_type" value="local" checked> Video dari folder komputer</label><label><input type="radio" name="source_type" value="url"> Link video eksternal</label></div>
<div id="localBox"><div class="source-row"><input name="external_url" id="external_url" type="text" placeholder="D:\Design\folder\video.mp4" required><button class="btn secondary" type="button" id="browseFilesBtn">Browse file</button></div><div id="selectedFiles" class="selected-files"></div><span class="help">Centang beberapa file di browser untuk menambahkannya sekaligus.</span></div>
<div id="urlBox" style="display:none"><input name="external_url" id="external_url_url" type="text" placeholder="https://contoh.com/video.mp4"><span class="help">Masukkan URL MP4/WebM atau YouTube.</span></div>
<div class="field" style="margin-top:12px"><label>URL thumbnail (opsional)</label><input name="thumbnail_url" id="thumbnail_url" type="url" placeholder="https://…"></div><span class="help" id="durationStatus">Durasi akan diambil otomatis dari file video.</span><video id="preview" controls playsinline style="display:none;width:100%;max-width:680px;max-height:360px;background:#111;margin-top:14px;border-radius:12px"></video></div></div>
<div class="form-actions"><button class="btn primary" id="submitBtn">Simpan video</button><button class="btn ghost" type="reset" id="resetBtn">Kosongkan form</button></div></form></section>
<div id="fileBrowser" hidden class="modal"><div class="file-browser-modal" role="dialog" aria-modal="true" aria-labelledby="fb-title"><header class="file-browser-header"><div class="title-group"><h2 id="fb-title">Pilih file video</h2><p>Centang file untuk memilih lebih dari satu.</p></div><button type="button" class="btn-close" id="closeFileBrowser" aria-label="Tutup">✕</button></header><div class="file-browser-toolbar"><label class="select-all-label"><input type="checkbox" id="selectAllFiles"> Pilih semua</label><span class="selection-count" id="fbSelectionCount">0 file dipilih</span></div><div class="file-browser-location"><label><input type="text" id="folderLocation" placeholder="D:\Video" aria-label="Path folder"><button type="button" class="btn secondary btn-open-location" id="openLocation">Buka lokasi</button></label></div><div class="file-browser-search"><input type="search" id="browserSearch" placeholder="Cari nama file…" aria-label="Cari nama file"></div><div class="file-browser-pinned empty" id="pinnedFoldersSection"><div class="pinned-header"><span>Folder tersimpan</span></div><div class="pinned-empty"><span>Belum ada folder tersimpan</span><button type="button" class="btn secondary btn-pin-current" id="pinFolder">☆ Pin folder saat ini</button></div></div><div class="file-browser-current"><div class="label">LOKASI SAAT INI</div><div class="path" id="browserPath"></div></div><div class="file-browser-list" id="browserEntries" role="listbox" aria-label="Daftar file dan folder"></div><footer class="file-browser-footer"><span class="selection-count" id="fbFooterSelectionCount">0 file dipilih</span><button type="button" class="btn primary btn-use-selected" id="useSelected" disabled>Gunakan file terpilih</button></footer></div></div>
<section class="panel"><form id="bulkDeleteForm" method="POST" action="{{ route('admin.videos.bulk-destroy') }}">@csrf @method('DELETE')<div class="browser-head"><div><h2>Daftar video</h2><p class="help">Pilih video yang ingin dihapus sekaligus.</p></div><div class="form-actions"><button class="btn ghost" type="button" id="selectAllVideos">Pilih semua</button><button class="btn danger" type="submit" onclick="return confirm('Hapus semua video yang dipilih?')">Hapus terpilih</button><input id="tableSearch" placeholder="Cari nama, kategori, model…" style="max-width:360px"></div></div><div class="table-wrap"><table><thead><tr><th><input type="checkbox" id="selectAllCheckbox" aria-label="Pilih semua video"></th><th>Video</th><th>Durasi</th><th>Kategori</th><th>Model</th><th>Sumber</th><th>Aksi</th></tr></thead><tbody id="videoRows">@foreach($videos as $video)<tr data-search="{{ strtolower($video->title.' '.$video->category->name.' '.$video->model_name) }}"><td><input type="checkbox" name="video_ids[]" value="{{ $video->id }}" class="video-checkbox" aria-label="Pilih {{ $video->title }}"></td><td><strong>{{ $video->title }}</strong></td><td>{{ $video->duration }}</td><td><div class="tag-list">@foreach($video->categories as $category)<span class="pill">{{ $category->name }}</span>@endforeach</div></td><td><div class="tag-list">@foreach($video->models as $model)<span class="pill model-pill">{{ $model->name }}</span>@endforeach</div></td><td><a href="{{ $video->playback_url }}" target="_blank" rel="noopener">Buka link ↗</a></td><td style="white-space:nowrap"><button class="btn secondary edit-btn" type="button" data-id="{{ $video->id }}" data-title="{{ $video->title }}" data-duration="{{ $video->duration }}" data-categories="{{ $video->categories->pluck('id')->implode(',') }}" data-models="{{ $video->models->pluck('id')->implode(',') }}" data-type="{{ $video->source_type }}" data-source="{{ $video->source_path }}" data-thumb="{{ $video->thumbnail_url }}">Edit</button><form method="POST" action="{{ route('admin.videos.destroy',$video) }}" style="display:inline">@csrf @method('DELETE')<button class="btn danger" onclick="return confirm('Hapus video ini?')">Hapus</button></form></td></tr>@endforeach</tbody></table></div><div class="pagination-wrap">{{ $videos->links() }}</div></section>
<script>
const form=document.getElementById('videoForm'),localInput=document.getElementById('external_url'),urlInput=document.getElementById('external_url_url'),preview=document.getElementById('preview'),durationInput=document.getElementById('duration'),status=document.getElementById('durationStatus'),browser=document.getElementById('fileBrowser'),entries=document.getElementById('browserEntries'),locationInput=document.getElementById('folderLocation'),searchInput=document.getElementById('browserSearch'),pinnedSection=document.getElementById('pinnedFoldersSection'),fbSelectionCount=document.getElementById('fbSelectionCount'),fbFooterSelectionCount=document.getElementById('fbFooterSelectionCount'),selected=new Map(),selectedTitles=new Map();let currentFolder='';

function updateSelectionCount(){const count=selected.size;fbSelectionCount.textContent=`${count} file dipilih`;fbFooterSelectionCount.textContent=`${count} file dipilih`;document.getElementById('useSelected').disabled=count===0;}
function sourceChanged(){const type=form.querySelector('[name=source_type]:checked').value;document.getElementById('localBox').style.display=type==='local'?'block':'none';document.getElementById('urlBox').style.display=type==='url'?'block':'none';localInput.disabled=type!=='local';urlInput.disabled=type!=='url';localInput.required=type==='local'&&selected.size===0;urlInput.required=type==='url'}form.querySelectorAll('[name=source_type]').forEach(x=>x.addEventListener('change',sourceChanged));sourceChanged();
document.querySelectorAll('.tag-search').forEach(input=>input.oninput=()=>document.querySelectorAll('#'+input.dataset.target+' label').forEach(label=>label.hidden=!label.dataset.name.includes(input.value.toLowerCase())));
preview.addEventListener('loadedmetadata',()=>{const seconds=Math.round(preview.duration);durationInput.value=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;status.textContent='Durasi otomatis: '+durationInput.value});
function previewLocal(path=localInput.value){if(!path)return;preview.src='{{ route('admin.videos.preview') }}?path='+encodeURIComponent(path);preview.style.display='block';if(!document.getElementById('title').value)document.getElementById('title').value=path.split(/[\\/]/).pop().replace(/\.[^.]+$/,'')}
function drawSelected(){const box=document.getElementById('selectedFiles');box.innerHTML='';selected.forEach((name,path)=>{const row=document.createElement('div');row.className='selected-file-row';const label=document.createElement('label');label.textContent=name;const input=document.createElement('input');input.type='text';input.name='file_titles[]';input.required=true;input.maxLength=180;input.value=selectedTitles.get(path)||name.replace(/\.[^.]+$/,'');input.oninput=()=>selectedTitles.set(path,input.value);const remove=document.createElement('button');remove.type='button';remove.className='btn danger';remove.textContent='Hapus';remove.onclick=()=>{selected.delete(path);selectedTitles.delete(path);drawSelected();sourceChanged()};row.append(label,input,remove);box.append(row)});sourceChanged();updateSelectionCount();}

function folderIcon(){return '<svg class="entry-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 21a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2h-9.5a2 2 0 0 1-1.68-.89L9.33 2.42A2 2 0 0 0 7.68 2H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2h16z"></path></svg>';}
function fileIcon(){return '<svg class="entry-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="23 7 16 12 23 17 23 7"></polygon><rect x="2" y="4" width="20" height="16" rx="2"></rect></svg>';}

async function openFolder(path=currentFolder,q=''){const params=new URLSearchParams();if(path)params.set('path',path);if(q)params.set('q',q);const response=await fetch('{{ route('admin.videos.files') }}?'+params);if(!response.ok){alert('Folder tidak bisa dibaca. Pastikan path berada di VIDEO_BROWSE_ROOT.');return}const data=await response.json();currentFolder=data.current;locationInput.value=data.current;document.getElementById('browserPath').textContent=data.current;entries.innerHTML='';if(data.parent){const back=document.createElement('div');back.className='file-entry';back.dataset.path=data.parent;back.innerHTML=folderIcon()+'<span class="entry-name">.. Kembali</span>';back.onclick=()=>openFolder(data.parent,searchInput.value);entries.append(back)}data.entries.forEach(item=>{const row=document.createElement('div');row.className='file-entry '+(item.type==='file'?'is-file':'');if(item.type==='file'){row.dataset.path=item.path;row.innerHTML='<input type="checkbox">'+fileIcon()+'<span class="entry-name">'+item.name+'</span>';const checkbox=row.querySelector('input[type="checkbox"]');checkbox.checked=selected.has(item.path);checkbox.onchange=()=>{checkbox.checked?selected.set(item.path,item.name):selected.delete(item.path);drawSelected()};}else{row.innerHTML=folderIcon()+'<span class="entry-name">'+item.name+'</span>';row.dataset.path=item.path;row.onclick=()=>openFolder(item.path,searchInput.value);}entries.append(row)});updateSelectAllCheckbox();}

function updateSelectAllCheckbox(){const allCheckboxes=entries.querySelectorAll('.is-file input[type=checkbox]');const checked=entries.querySelectorAll('.is-file input[type=checkbox]:checked').length;const total=allCheckboxes.length;const selectAll=document.getElementById('selectAllFiles');if(selectAll){selectAll.checked=total>0&&checked===total;selectAll.indeterminate=checked>0&&checked<total}}

document.getElementById('selectAllFiles').onclick=()=>{const boxes=entries.querySelectorAll('.is-file input[type=checkbox]');const allChecked=[...boxes].every(b=>b.checked);boxes.forEach(b=>{b.checked=!allChecked;b.dispatchEvent(new Event('change'))});drawSelected();}

function renderPins(){const pins=JSON.parse(localStorage.getItem('videohub-pinned-folders')||'[]');const section=pinnedSection;if(!pins.length){section.classList.add('empty');const emptyEl=section.querySelector('.pinned-empty');if(emptyEl)emptyEl.style.display='flex';return}section.classList.remove('empty');const emptyEl=section.querySelector('.pinned-empty');if(emptyEl)emptyEl.style.display='none';let container=section.querySelector('.pinned-container');if(!container){container=document.createElement('div');container.className='pinned-container';section.querySelector('.pinned-header').after(container);}container.innerHTML='';pins.forEach(path=>{const wrap=document.createElement('div');wrap.className='pinned-folder-item';wrap.innerHTML='<span class="pinned-path" title="'+path+'">'+path+'</span><button type="button" class="btn-pin-remove" title="Hapus pin">×</button>';wrap.querySelector('.pinned-path').onclick=()=>openFolder(path);wrap.querySelector('.btn-pin-remove').onclick=()=>{localStorage.setItem('videohub-pinned-folders',JSON.stringify(pins.filter(item=>item!==path)));renderPins()};container.append(wrap)});}
document.getElementById('browseFilesBtn').onclick=()=>{browser.hidden=false;renderPins();openFolder()};document.getElementById('closeFileBrowser').onclick=()=>browser.hidden=true;document.getElementById('openLocation').onclick=()=>openFolder(locationInput.value.trim(),searchInput.value);searchInput.oninput=()=>openFolder(currentFolder,searchInput.value);document.getElementById('pinFolder').onclick=()=>{if(!currentFolder)return;const pins=JSON.parse(localStorage.getItem('videohub-pinned-folders')||'[]');if(!pins.includes(currentFolder))pins.push(currentFolder);localStorage.setItem('videohub-pinned-folders',JSON.stringify(pins));renderPins()};document.getElementById('useSelected').onclick=()=>{if(!selected.size){alert('Pilih minimal satu file.');return}const first=[...selected.entries()][0];localInput.value=first[1];previewLocal(first[1]);browser.hidden=true;drawSelected()};
form.addEventListener('submit',()=>{document.querySelectorAll('.selected-file-hidden').forEach(input=>input.remove());selected.forEach((name,path)=>{const input=document.createElement('input');input.type='hidden';input.name='selected_files[]';input.value=path;input.className='selected-file-hidden';form.append(input)})});
document.querySelectorAll('.edit-btn').forEach(button=>button.onclick=()=>{form.action='{{ url('/admin/videos') }}/'+button.dataset.id;form.querySelector('[name=_method]')?.remove();const method=document.createElement('input');method.type='hidden';method.name='_method';method.value='PUT';form.append(method);document.getElementById('title').value=button.dataset.title;document.getElementById('duration').value=button.dataset.duration||'';document.querySelectorAll('[name="category_ids[]"],[name="model_ids[]"]').forEach(input=>input.checked=(button.dataset.categories+','+button.dataset.models).split(',').includes(input.value));document.getElementById('thumbnail_url').value=button.dataset.thumb||'';form.querySelector('[name=source_type][value="'+button.dataset.type+'"]').checked=true;if(button.dataset.type==='url')urlInput.value=button.dataset.source;else localInput.value=button.dataset.source;sourceChanged();document.getElementById('form-heading').textContent='Edit video';document.getElementById('submitBtn').textContent='Simpan perubahan';document.getElementById('video-form').scrollIntoView({behavior:'smooth'})});
document.getElementById('resetBtn').onclick=()=>setTimeout(()=>{form.action='{{ route('admin.videos.store') }}';form.querySelector('[name=_method]')?.remove();selected.clear();selectedTitles.clear();document.getElementById('selectedFiles').innerHTML='';document.getElementById('form-heading').textContent='Tambah video baru';document.getElementById('submitBtn').textContent='Simpan video';sourceChanged()},0);
document.getElementById('tableSearch').oninput=e=>document.querySelectorAll('#videoRows tr').forEach(row=>row.hidden=!row.dataset.search.includes(e.target.value.toLowerCase()));
const videoChecks=[...document.querySelectorAll('.video-checkbox')],allCheck=document.getElementById('selectAllCheckbox');function setAllVideos(checked){videoChecks.forEach(input=>input.checked=checked);allCheck.checked=checked}document.getElementById('selectAllVideos').onclick=()=>setAllVideos(!videoChecks.every(input=>input.checked));allCheck.onchange=()=>setAllVideos(allCheck.checked);videoChecks.forEach(input=>input.onchange=()=>{allCheck.checked=videoChecks.length>0&&videoChecks.every(item=>item.checked)});
</script>
@endsection
