<!doctype html>
<html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>@yield('title', 'VidoHub')</title>
<style>
:root{--bg:#f7f8fc;--text:#182238;--muted:#718096;--line:#e8ebf3;--pink:#ec2877;--soft:#fff0f6;--blue:#edf5ff;--red:#d93655}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:15px/1.5 Inter,system-ui,-apple-system,sans-serif}
header{display:flex;justify-content:space-between;align-items:center;padding:18px clamp(18px,5vw,56px);background:#fff;border-bottom:1px solid var(--line);gap:16px;flex-wrap:wrap}
.brand{font-size:25px;font-weight:850;letter-spacing:-.7px}.brand span{color:var(--pink)}a{color:var(--pink);text-decoration:none}
main{max-width:1240px;margin:28px auto;padding:0 20px}.btn{display:inline-block;border:0;border-radius:10px;padding:10px 14px;font-weight:750;cursor:pointer;font:inherit;font-size:14px}.primary{background:var(--pink);color:white}.secondary{background:var(--soft);color:var(--pink)}.danger{background:#fff0f2;color:var(--red)}.ghost{background:#f2f4f9;color:#45516a}
.panel,.stat,.info{background:white;border:1px solid var(--line);border-radius:16px;padding:20px;margin-bottom:22px}.heading{display:flex;justify-content:space-between;align-items:end;gap:16px;flex-wrap:wrap;margin-bottom:22px}.heading h1{font-size:clamp(25px,3vw,34px);margin:0}.heading p{margin:5px 0 0;color:var(--muted)}
.stats{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:15px;margin-bottom:22px}.stat small{color:var(--muted);font-weight:650}.stat strong{display:block;font-size:28px;margin-top:5px}
.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.field{display:flex;flex-direction:column;gap:7px}.full{grid-column:1/-1}label{font-size:13px;font-weight:750;color:#46536b}
input,select{width:100%;border:1px solid #dfe4ee;border-radius:10px;padding:12px 13px;background:#fff;color:var(--text);font:inherit;outline:none}input:focus,select:focus{border-color:var(--pink);box-shadow:0 0 0 3px #ec28771a}
.help,.muted{font-size:12px;color:var(--muted)}.source-tabs{display:flex;gap:8px;margin-bottom:12px}.source-tabs label{padding:9px 13px;background:#f7f8fc;border-radius:9px;cursor:pointer}.source-tabs input{width:auto}
table{width:100%;border-collapse:collapse;min-width:740px}th,td{text-align:left;padding:13px 12px;border-bottom:1px solid var(--line);vertical-align:middle}th{font-size:12px;text-transform:uppercase;color:var(--muted);background:#fafbfe}.table-wrap{overflow-x:auto}.pill{display:inline-block;background:var(--soft);color:#b51b5b;border-radius:7px;padding:4px 8px;font-size:12px;font-weight:750}.notice{padding:12px 14px;background:#fff8e8;border:1px solid #f5e2b5;border-radius:10px;color:#795c20;font-size:13px;margin-top:16px}
.alert{padding:12px 15px;border-radius:10px;background:#eaf8f0;color:#17633f;margin-bottom:16px}.errors{background:#fff0f2;color:#a51e3c;padding:12px 18px;border-radius:10px;margin-bottom:16px}
.cards{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:18px}.card{background:#fff;border:1px solid var(--line);border-radius:14px;overflow:hidden;color:inherit}.thumb{aspect-ratio:16/9;background:#e9ebf2;position:relative}.thumb img{width:100%;height:100%;object-fit:cover}.thumb .duration{position:absolute;right:8px;bottom:8px;background:#151824dd;color:white;padding:2px 7px;border-radius:5px;font-size:12px}.copy{padding:12px}.copy strong{display:block;margin-bottom:8px}.tags{display:flex;gap:7px;flex-wrap:wrap}.player-shell{background:#05060a;border-radius:16px;overflow:hidden;position:relative}.player{aspect-ratio:16/9;position:relative}.player video{width:100%;height:100%;object-fit:contain;display:block}.overlay-tools{position:absolute;right:14px;bottom:14px;display:flex;gap:8px;z-index:4;opacity:1;transition:opacity .25s}.controls-hidden .overlay-tools{opacity:0;pointer-events:none}.overlay-tools button{background:#111c;color:#fff;border:1px solid #ffffff55;padding:9px 12px;border-radius:10px;cursor:pointer;font-weight:750}.player-shell:fullscreen{width:100vw;height:100vh;display:flex;align-items:center;justify-content:center}.player-shell:fullscreen .player{width:100%;height:100%;aspect-ratio:auto}.info{margin-top:20px}.info h1{margin-top:0}.metadata{display:flex;gap:10px;flex-wrap:wrap}.metadata span{padding:8px 12px;background:#f7f8fc;border-radius:9px}.rec-title{font-weight:750}@media(max-width:850px){.cards{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:650px){.stats,.form-grid{grid-template-columns:1fr}.full{grid-column:auto}.cards{grid-template-columns:1fr 1fr}main{padding:0 13px}.panel{padding:16px}}
</style></head><body>
<header><a class="brand" href="{{ route('videos.index') }}" style="color:inherit">Vido<span>Hub</span></a><nav style="display:flex;gap:10px;align-items:center"><a class="btn secondary" href="{{ route('videos.index') }}">Koleksi</a><a class="btn secondary" href="{{ route('admin.videos.index') }}">Admin</a></nav></header>
<main>
@if(session('success'))<div class="alert">{{ session('success') }}</div>@endif
@if($errors->any())<div class="errors"><strong>Periksa kembali:</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@yield('content')
</main>
</body></html>