<!doctype html>
<html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>@yield('title', 'VidoHub')</title>
<style>
:root{--bg:#f7f8fc;--text:#182238;--muted:#718096;--line:#e8ebf3;--pink:#ec2877;--soft:#fff0f6;--blue:#edf5ff;--red:#d93655}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:15px/1.5 Inter,system-ui,-apple-system,sans-serif}
header{display:flex;justify-content:space-between;align-items:center;padding:18px clamp(18px,5vw,56px);background:#fff;border-bottom:1px solid var(--line);gap:16px;flex-wrap:wrap}
.brand{font-size:25px;font-weight:850;letter-spacing:-.7px;transition:transform .2s ease}.brand span{color:var(--pink)}a{color:var(--pink);text-decoration:none}.brand:hover{transform:translateY(-1px)}.main-nav{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.main-nav .btn{transition:transform .2s ease,box-shadow .2s ease,background .2s ease}.main-nav .btn:hover{transform:translateY(-2px);box-shadow:0 8px 18px #18223818;background:#ffe4f0}.main-nav .btn:focus-visible,.btn:focus-visible,a:focus-visible{outline:3px solid #ec287766;outline-offset:2px}
main{max-width:1240px;margin:28px auto;padding:0 20px}.btn{display:inline-block;border:0;border-radius:10px;padding:10px 14px;font-weight:750;cursor:pointer;font:inherit;font-size:14px}.primary{background:var(--pink);color:white}.secondary{background:var(--soft);color:var(--pink)}.danger{background:#fff0f2;color:var(--red)}.ghost{background:#f2f4f9;color:#45516a}
.panel,.stat,.info{background:white;border:1px solid var(--line);border-radius:16px;padding:20px;margin-bottom:22px;box-shadow:0 6px 22px #18223808}.panel>h2{margin:0 0 6px;font-size:19px;letter-spacing:-.2px}.heading{display:flex;justify-content:space-between;align-items:end;gap:16px;flex-wrap:wrap;margin-bottom:22px}.heading h1{font-size:clamp(25px,3vw,34px);margin:0}.heading p{margin:5px 0 0;color:var(--muted)}
.stats{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:15px;margin-bottom:22px}.stat small{color:var(--muted);font-weight:650}.stat strong{display:block;font-size:28px;margin-top:5px}
.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.field{display:flex;flex-direction:column;gap:7px}.full{grid-column:1/-1}label{font-size:13px;font-weight:750;color:#46536b}
input,select{width:100%;border:1px solid #dfe4ee;border-radius:10px;padding:12px 13px;background:#fff;color:var(--text);font:inherit;outline:none}input:focus,select:focus{border-color:var(--pink);box-shadow:0 0 0 3px #ec28771a}
.help,.muted{font-size:12px;color:var(--muted)}.source-tabs{display:flex;gap:8px;margin-bottom:12px}.source-tabs label{padding:9px 13px;background:#f7f8fc;border-radius:9px;cursor:pointer}.source-tabs input{width:auto}
.admin-columns{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:22px}.admin-section{border-top:3px solid var(--soft);padding-top:17px}.quick-form,.source-row,.form-actions,.browser-head{display:flex;gap:10px;align-items:center}.quick-form input{flex:1}.quick-form select{max-width:170px}.tag-list{display:flex;gap:7px;flex-wrap:wrap;margin-top:13px}.tag-item form{display:inline}.tag-item button{border:0;background:transparent;color:inherit;cursor:pointer;font-weight:800;padding:0}.model-pill{background:var(--blue);color:#3474c5}.check-list{display:flex;flex-direction:column;gap:6px;max-height:145px;overflow-y:auto;border:1px solid var(--line);border-radius:10px;padding:10px;background:#fbfcff}.check-list label{font-weight:500;padding:7px;border-radius:7px;cursor:pointer}.check-list label:hover{background:var(--soft)}.check-list input{width:auto;margin-right:6px}.source-row input{flex:1}.modal{position:fixed;inset:0;background:#0008;z-index:20;padding:5vh 15px}.browser-panel{max-width:800px;margin:auto;max-height:90vh;overflow:auto}.browser-head{justify-content:space-between;flex-wrap:wrap}.browser-entries{display:grid;gap:8px;margin-top:12px}.browser-entries .btn{text-align:left;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.file-entry:hover{transform:translateX(2px);box-shadow:0 4px 12px #18223812}
table{width:100%;border-collapse:collapse;min-width:740px}.pagination-wrap{margin-top:18px}.pagination-wrap nav{display:flex;justify-content:center}.pagination-wrap nav>div:first-child{display:none}.pagination-wrap nav>div:last-child{display:flex;gap:6px}.pagination-wrap a,.pagination-wrap span{display:inline-flex;align-items:center;justify-content:center;min-width:34px;height:34px;padding:0 9px;border:1px solid var(--line);border-radius:8px;background:#fff;color:var(--text)}.pagination-wrap a:hover{border-color:var(--pink);color:var(--pink)}.pagination-wrap span[aria-current]{background:var(--pink);border-color:var(--pink);color:#fff}th,td{text-align:left;padding:13px 12px;border-bottom:1px solid var(--line);vertical-align:middle}th{font-size:12px;text-transform:uppercase;color:var(--muted);background:#fafbfe}.table-wrap{overflow-x:auto}.pill{display:inline-block;background:var(--soft);color:#b51b5b;border-radius:7px;padding:4px 8px;font-size:12px;font-weight:750}.notice{padding:12px 14px;background:#fff8e8;border:1px solid #f5e2b5;border-radius:10px;color:#795c20;font-size:13px;margin-top:16px}
.alert{padding:12px 15px;border-radius:10px;background:#eaf8f0;color:#17633f;margin-bottom:16px}.errors{background:#fff0f2;color:#a51e3c;padding:12px 18px;border-radius:10px;margin-bottom:16px}
.cards{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:20px}.card{background:#fff;border:1px solid var(--line);border-radius:16px;overflow:hidden;color:inherit;box-shadow:0 5px 18px #1822380b;transition:transform .22s ease,box-shadow .22s ease,border-color .22s ease}.card:hover{transform:translateY(-6px);box-shadow:0 16px 30px #1822381c;border-color:#f5b4d0}.thumb{aspect-ratio:16/9;background:#e9ebf2;position:relative;overflow:hidden}.thumb video,.thumb img{width:100%;height:100%;object-fit:cover;display:block}.thumb-fallback{position:absolute;inset:0}.thumb .duration{position:absolute;right:9px;bottom:9px;background:#151824dd;color:white;padding:3px 8px;border-radius:6px;font-size:12px}.copy{padding:14px}.copy strong{display:block;margin-bottom:9px}.tags{display:flex;gap:7px;flex-wrap:wrap}.selected-files{display:grid;gap:8px;margin-top:8px}.selected-file-row{display:grid;grid-template-columns:minmax(130px,.7fr) minmax(180px,1fr) auto;gap:8px;align-items:center;padding:8px 10px;background:#fafbfe;border:1px solid var(--line);border-radius:10px}.selected-file-row label{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.selected-files button{border:0;background:transparent;color:inherit;cursor:pointer;font-weight:800}.pin-item{display:inline-flex;gap:4px;align-items:center}.file-entry{display:flex;gap:8px;align-items:center;transition:transform .18s ease,box-shadow .18s ease}.file-entry input{width:auto}.live-search{margin-bottom:22px}.live-search input{font-size:16px;padding:15px 16px}.controls-hidden .overlay-tools{opacity:0;pointer-events:none}.overlay-tools button{background:#111c;color:#fff;border:1px solid #ffffff55;padding:9px 12px;border-radius:10px;cursor:pointer;font-weight:750}.player-shell:fullscreen{width:100vw;height:100vh;display:flex;align-items:center;justify-content:center}.player-shell:fullscreen .player{width:100%;height:100%;aspect-ratio:auto}.info{margin-top:20px}.info h1{margin-top:0}.metadata{display:flex;gap:10px;flex-wrap:wrap}.metadata span{padding:8px 12px;background:#f7f8fc;border-radius:9px}.rec-title{font-weight:750}@media(max-width:850px){.cards{grid-template-columns:repeat(2,minmax(0,1fr))}.admin-columns{grid-template-columns:1fr}}@media(max-width:650px){.stats,.form-grid{grid-template-columns:1fr}.full{grid-column:auto}.cards{grid-template-columns:1fr 1fr}main{padding:0 13px}.panel{padding:16px}.source-row{align-items:stretch;flex-direction:column}.quick-form select{max-width:none}.selected-file-row{grid-template-columns:1fr}.selected-file-row .btn{width:100%}}
.detail-player-shell{max-width:900px;margin:0 auto;background:#05060a}.detail-player-shell .player{max-height:68vh;display:flex;align-items:center;justify-content:center}.detail-player-shell video,.detail-player-shell iframe{max-width:100%;max-height:68vh;width:100%;height:auto;object-fit:contain}@media(max-width:850px){.cards{grid-template-columns:repeat(2,minmax(0,1fr))}.admin-columns{grid-template-columns:1fr}}@media(max-width:650px){.stats,.form-grid{grid-template-columns:1fr}.full{grid-column:auto}.cards{grid-template-columns:1fr 1fr}main{padding:0 13px}.panel{padding:16px}.source-row{align-items:stretch;flex-direction:column}.quick-form select{max-width:none}.selected-file-row{grid-template-columns:1fr}.selected-file-row .btn{width:100%}}
</style></head><body>
@php($navCategories = \App\Models\Category::whereNotNull('page_key')->orderBy('id')->get())
<header><a class="brand" href="{{ route('videos.index') }}" style="color:inherit">Vido<span>Hub</span></a><nav class="main-nav"><a class="btn secondary" href="{{ route('videos.index') }}">Koleksi</a>@foreach($navCategories as $navCategory)<a class="btn secondary" href="{{ route('videos.index', ['category' => $navCategory->slug]) }}">{{ $navCategory->name }}</a>@endforeach<a class="btn secondary" href="{{ route('admin.videos.index') }}">Admin</a></nav></header>
<main>
@if(session('success'))<div class="alert">{{ session('success') }}</div>@endif
@if($errors->any())<div class="errors"><strong>Periksa kembali:</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@yield('content')
</main>
</body></html>